
export const FORM_ADD_FIXSENDPERSON = 'FORM_ADD_FIXSENDPERSON'; //添加固定抄送人
export const FORM_DEL_FIXSENDPERSON = 'FORM_DEL_FIXSENDPERSON'; //删除固定抄送人

export const FORM_ADD_FIXAPPROVER = 'FORM_ADD_FIXAPPROVER'; // 添加固定审批人
export const FORM_DEL_FIXAPPROVER = 'FORM_DEL_FIXAPPROVER'; // 删除固定审批人 

export const FORM_DRAG_FIXAPPROVER = 'FORM_DRAG_FIXAPPROVER'; //固定审批人拖拽结束事件
export const FORM_CHANGE_FIXAPPROVER = 'FORM_CHANGE_FIXAPPROVER';